### ISSUE TITLE
UI for mobile?

### ISSUE THREAD

**Issue by tdlio** [muharamdani/poe#15]
What's the best way to get a ui running for this on mobile? Honestly Poe didn't have an exceptional UI so just something equal to it at a minimum.
 Ideally i would want one to run locally on my burner. "Off the grid" is still a dream ya know

**Comment by muharamdani** [comment]
Since this is using node, to create a UI you can use any number of frameworks and tools that are available like React Native or Ionic.

For the connection to poe api, you can look up into src/client_manual.ts for references.

Overall, there are many options available for creating a UI for this poe client on mobile. The best approach will depend on your specific requirements and preferences.

**Comment by tdlio** [comment]
Many thanks for the response. I was asking about a template pre-made of the basic chat interface: messages container, list view on the sidebar of chat history, etc. The standard "messenger" look Telegram / WhatsApp / Poe to a lesser degree all have. Then I want to work off of that to make my own. DOn't need Poe's API for their backend, simply a front end template. Not a big UI guy so want to speed this process ahead if possible.

**Comment by muharamdani** [comment]
Ah, my bad for misunderstanding, if you're looking for chat app template, you can take a loot at this link https://github.com/topics/android-chat-application. 

Note: Since I'm not FE/mobile app dev, I'm not quite sure what am I sharing is relevant to you or not, but I hope this help.
